build: false

skip_branch_with_pr: true

environment:
  matrix:
    - nodejs_version: "Current"

configuration: Release
platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - ps: If ($env:nodejs_version -eq "Current") { npm run prebuild }

artifacts:
  - path: prebuilds
    name: $(APPVEYOR_REPO_TAG_NAME)-win-$(PLATFORM)
    type: zip

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    draft: false
    prerelease: true
    auth_token:
      secure: nkFg7/bdt+M1Pn2d9JTSFXgUYixu6lEPwL3w+epR7LxYe6c9K7b/7c0dijrRRu6wZ+7mN/LbSoDXeqm4CxzeeZUSS1rRau6oVRwi+nX8WhhjmmRfjsLEO7qVCM8KJJ2QD36ZbvpaL1GLmy0PGdwHO4AHMEkFmV1aK/hhzPzfRqHsgLAPVdZN4++prRlq2+ffvtX/szIH4s7vs820vLqtQvQYIcaDwdfrr/Ab6FafywPgRi6rxPyuh9R8gapQ9y1ucJ5g5GxUERdGg2Py1LnVv89QZFgSBDHIxDgjxXdt1UkGTAdmwnBrjUqrV2RmjHvXKDRYDUaf79oc5sSOjSDCStOAjhHN4F0ylODuJRl4GN6WOyIKMGq6jEYmkoHqlfWoldrn2iPGRFWzK2fnu2K0qxtIyjmFN51jWojCqfZqTz9TJmqr1q+JfN1hh2XVPSFUz8emdo9w8dY5X2bsVHo3rxYEpfH9BR8M2DdEOcl7aAlBd8r7Epqm57x2kLFokXHnqXlbybQtDAFkg7JC/1Glw6WzPqqokDdoofSQmah5Eyz4v4veR8XKP+ruzAYi+RAT9wMX5b9wyHURNYgkJnHz3TdMXVeD/jCeH/v4w/RqeD+GFaVx/4drkNtmd38vjSXBi8PAPcQJTLPnEuDVqEQGsOWKbHUqeVPk7SIRE8awaS78zMOopZw6C3+eA08wFeWnP0GteylKlFEGTMjAXppXC7YqbkTsuO2S62pdBfVQ3RrS2LPeUVTXQttUalArsPjFaQ3sV9VUflD+SPkiRh5HhFASTpybVPlOgCyuNOQIr5PbqsaYjSvXBrC2jA0kMeBGxTbLWA6zROd8Hb0bOMLMT3HUrGyv4SVtPGsHCuRHW4A93BBTzqKLFO2Gro+57r1/u1S9KPhMzhJe4ZDRA9Z8wRquVxEaz8GwqicdwrgRZ0RJvDQapbD+qGQu710B5ovMuTxLm0cwQuDAEYvsYndxDq38RMrTMuNq0yoPJs9LMQ7Nxfi4tu2Gfbx0iVgP96HhZa4oJ9xqp46s20HuhEiF1Q/8V5+ETbOrOC3uJbdx3uLJtSxQO6yZ2DHB9j0EcPNuSQPlUCrR26xFtRapriy6GR/7D4gV0pvp8uUVwL2JTGowGVZr5ubN0JhaFQt9Oo0mXCUvD6Y92E4F8hC8KVnMJ+lYJr5V4BpIUUZ63NF4dwyxOSpLdnOkre1HmN3EZYzwJ56wEwzYw0dxK8nCprbH+qYI49ZWPkmFnmAj0OYjwCeG3N9bM9qOELAeHLKCVK5k/WUuLj+heFUKZulfRYOSAeax/et/+XwD/t4NHjp4eyuHrrw/zCIewRaBZvVrEVCMzyYCaN/iRwVJDGn6FCsDYltRUAGC7K12/rvsQ0wO3lj/5JoYieOeuJQa4eSiJJeYge/hh5BYV1kM1HDaPVrc5Zf3IP4ykwDCeOCarbiOili3Hf/jnhP2Yv80lECfrEB8sMIeOPwQzEqlh2gSw2+yqaZBb1CRMEWFTEO8Yn/6PSTK5sfcZ9Wwxt/8YxhUd9SoNoo/D1x67dJ0KUf+qaJudxFUcthqFjYN7Cb8sTXwv1GrxALcI+T4DjYa/OiMPdIluoZjCnfXzCunVR8ln8qSbxgOuCGltkkYf0YoXkZQ7Xj0gB8MKi/a3FukYuWTLnu7FyDCHy/xVDoCz7OssT/SvIJ51sudYnpeaRWWylhQ8z/fGlZ90L3s6uDbVvM3oYDvzcTdWC0OXaC/vF1YxEJdT5FzazEknnqqfnas+0CQoCRXuXU6N6956bEGsLSF0biKk3otL8IU6Be2OeCrX0FEfAXOShVcBVguk918v8A8Uunk9iSBCDao3cMBDukyoFLoTkrJsDAX0wnt/j0EmUASU7rC83ecfUTSJ9PfldUSsGOiSpQsOxDn7wAwki54cucbjvTC6SuqIomCqgSppHgy/a1d/o1Wzo5o90A2Rq6ky1yNG8Cgb2nlp5vB1wP6VOcfpzWqVTlxyT3GycUK0nCIpl3sKmWgZfTpTvOa03paWHmexEYoCB4hs3FFb+R7nr5rzm4xJ3AKKHA3i/2Nb6ICwrRBaDCGqXI6oDZ66m89oByjx/cZ85/opongzDgR2r4Jx/lTzFY71s4eK4CC+rIHdVtqTDoVf4coAQgH9EN+L2d4KhKoJg6vZMW9u8ooxqCOA1mT5JQIwVgVZ5H7IL+k3u56QaWn+IYLVZbtMu7b+gGlR1KbiPyyxYXnWWwngwqMoIeb094mH39j/Wtg0Dj24sCljdZJpjwyUJyFCFqwvjB950dcqyDBqrehwnh5XiyZRRDq9byZNdcrY1r8GHGNNLCBs1JNqAQpu2LTrgWXgL0sqrXT1x4lnKcDbvKunhSC4QHgPgRWZye1EKGs4v0kklc93wbY6xzeL+mOH1x0jFfN5xGVx3WgLEjN66901Ngx21Sx5X9oh1EIdYtfWFYBT315vqO+G+t38l/QXPiu3o89EVYGcQc/F5c5HtkAwkyEG0JzlSiXFdYJsdOGsVGFA6GvsEsd9E2oa/OWLPqpZL5MicnLufFuUNb4r4Sx8TAUHdTASkfBgDp6E3wbAhZ2kwrqrrkpG/8+XWIGGs4VdhFxvM5qar6Ayfm3p8VQAjGECGs6X9KI2K4s+gApvQm7mphP+YDLSABVpUNehVFK5nJkz/sh7hqnrlFdea0Xa/iMIRe75e4yTeI7f34C1wFAailm+5Vs3ds30HzaAXNk3IRgVB8zf4fDs5pX6s4q1H8MDAI9ITh3bClqTk9GVFeHvjD2013oNO3hB6hTpV9M51G7XhAjfcwWpaZy6VHd8nTRK2QNOIi2YcQZYY3+wCnqHYHPX9+CWy+tP3+bo4CZ3b2Vtj9C9uCgsvXIFnuoVlYlz7THODDhbKEv6jNh2ITthnBsAIHTucy4r3dWCgyb0AIbbqePc2+DrfEcceu0EbtVj9fAieJye3mX+fVoSwtkC6bBTptjhsSfx2SCchL0E/BOZ16EJAUg4+2eRTyyfi8QuHMD4mWYBcb24HvQtBdvxxrIyCKT+4b+EtjRv5i/4ETYkgiv3ppHV26BNpv0MbR8Zhn0xhSgru88dvmblVO+oHSSAM3otwWGNlVeOLBO80oUt11K2Xe2s2orwjZBfnM/AEUXRLXxDkvdw97Ngl2+tRMG+JGfz9docfDwl+Vbd6TVkiut09VnXam/CHELqbvewcJuUAIrpcOlH9t+Y0PCV/oPdV+mAYKuP0kBf2fXK82dOCP0rL0tS2KPxPWdPaQyE31uuNmzYM0VYv3fH5McnCp5Hv5wGzsBR2TJ0Iiu4Z9/MA+9hPEWNH9oVHNZUH9sNTs3osnp6EfEu2nnzydb+ZKisuQe6gV9KBGAE8cX9b2GQd/2Fi5EI4z15iQ8FPa/mbfXSLtro3QFLH+/5rKIripLVuC4GwW9MA20L+Dq0+cNyuaIYJfCVel6GxOwA7p5lTZQRJG/nZJEuoXJsdaawqA4fXvk6NYLMhDuHkBY6k5uAKTujR8U+Cb9iuyKw0PFvnKyyg4H7fRpDZVSVoJx4ckG6dCzEWUxcgZVfKcsGALtYXuUSPAaNLznSVs3rxumqKzsPdPuWuCc7NM0L3H+sqXCPoNMoJrgfkScDtlDJ1pS5z4LnCaBrwsPgIxpk0OgyEv2aCYCeZyA7xoE3MnOlOK6IUs3ZAt6PY7HRwVC26NTYd8tt+IjOL57/gdT2DmZ2fAMHkaNfIzmWu2WsVy+yCGA9uH02GTkCvANDT/nQ8jzGb2GcRr7wXeDPEsIj+r4fH6eFPFfy922GJfK8uMef5fatk0d0dIfIAosMbIwELOdG1DrM3+2AojQrS4rE/ZSdL26QbCZfnx6D1q0pruplZpGr2mdd/6BDpYU+V7NMrmBl/KGXoTXoeaYtPaLraLV1we3O+nEYyq1r7seLfrVRIYWrTtjiPr7CxKQIdC4HzEwNC3exxz1Jh7LgIg2kaimyqE/tdWxZCcegLuhg/k1gDdcwj7MU1U0RlT/Wb4ofLyZwnVEzSHYurxe/9b7/SfWnckyu7KzCZUVomyDjT9mt+J7SkXvNuJM2rv8IvJJJg2C6YCL9A3T7wm1J0vLJSR
    on:
      appveyor_repo_tag: true
      nodejs_version: "Current"
